# Generated by Django 6.0.1 on 2026-02-23 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('party_type', models.CharField(choices=[('individual', 'individual'), ('organisation', 'organisation')], max_length=32)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postcode', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(max_length=64)),
                ('data', models.JSONField()),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='organisations/logos/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('turnstile_success', models.BooleanField(default=False)),
                ('turnstile_error_codes', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='received', max_length=32)),
            ],
            options={
                'verbose_name': 'ADMIN - Application',
                'verbose_name_plural': 'ADMIN - Applications',
                'indexes': [models.Index(fields=['status'], name='membership__status_1cf474_idx'), models.Index(fields=['created_at'], name='membership__created_e5ab97_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeclarationForm',
            fields=[
                ('form_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('declaration_set', models.TextField()),
                ('version', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Declaration Form',
                'verbose_name_plural': 'Declaration Forms',
                'indexes': [models.Index(fields=['declaration_set', 'is_active'], name='membership__declara_fadc9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='individual', serialize=False, to='membership.party')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('preferred_pronouns', models.TextField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('preferred_contact_method', models.TextField(blank=True, null=True)),
                ('age_range', models.TextField(blank=True, null=True)),
                ('ethnic_background', models.TextField(blank=True, null=True)),
                ('ethnic_background_other', models.TextField(blank=True, null=True)),
                ('disability_health_condition', models.TextField(blank=True, null=True)),
                ('how_did_you_hear_about_fis', models.TextField(blank=True, null=True)),
                ('why_join_fis', models.TextField(blank=True, null=True)),
                ('digital_signature', models.TextField(blank=True, null=True)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('volunteer_occupation_current_role', models.TextField(blank=True, null=True)),
                ('volunteer_areas_of_expertise', models.TextField(blank=True, null=True)),
                ('volunteer_areas_of_expertise_other', models.TextField(blank=True, null=True)),
                ('volunteer_why_volunteer', models.TextField(blank=True, null=True)),
                ('volunteer_time_availability', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Party - Individual',
                'verbose_name_plural': 'Party - Individuals',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organisation', serialize=False, to='membership.party')),
                ('org_name', models.TextField(blank=True, null=True)),
                ('website_social', models.TextField(blank=True, null=True)),
                ('org_type', models.TextField(blank=True, null=True)),
                ('org_type_other', models.TextField(blank=True, null=True)),
                ('company_charity_number', models.TextField(blank=True, null=True)),
                ('mission_purpose', models.TextField(blank=True, null=True)),
                ('service_areas', models.TextField(blank=True, null=True)),
                ('visibility_preference', models.TextField(blank=True, null=True)),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='organisations/logos/')),
                ('alignment_with_fis_mission', models.TextField(blank=True, null=True)),
                ('collaboration_interests', models.TextField(blank=True, null=True)),
                ('collaboration_interests_other', models.TextField(blank=True, null=True)),
                ('org_activity_beneficiaries_good_food_approach', models.TextField(blank=True, null=True)),
                ('healthier_fairer_food_contribution', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Party - Organisation',
                'verbose_name_plural': 'Party - Organisations',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type_code', models.CharField(max_length=2)),
                ('class_code', models.CharField(max_length=2)),
                ('duration', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('share_capital', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('declaration_set', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'indexes': [models.Index(fields=['active'], name='membership__active_dfb0be_idx'), models.Index(fields=['class_code', 'type_code'], name='membership__class_c_4670c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('enrollment_code', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('enrollment_class', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('approved', 'approved'), ('cancelled', 'cancelled')], default='pending', max_length=16)),
                ('entered_in_register_by_name', models.TextField(blank=True, null=True)),
                ('entered_in_register_by_date', models.DateField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('serial_number', models.IntegerField(blank=True, null=True)),
                ('agreed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='membership.party')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='membership.plan')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('declarations_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('conflict_of_interest', models.BooleanField(blank=True, null=True)),
                ('conflict_of_interest_details', models.TextField(blank=True, null=True)),
                ('conflict_of_interest_details_accurate_info_declaration', models.BooleanField(blank=True, null=True)),
                ('data_contact_consent', models.BooleanField(blank=True, null=True)),
                ('data_withdrawal_acknowledgement', models.BooleanField(blank=True, null=True)),
                ('commitment_accepted', models.BooleanField(blank=True, null=True)),
                ('ind_voting_share_acknowledged', models.BooleanField(blank=True, null=True)),
                ('ind_voting_eligibility_confirmed', models.BooleanField(blank=True, null=True)),
                ('org_voting_rights_terms_accepted', models.BooleanField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='membership.declarationform')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='membership.enrollment')),
            ],
            options={
                'verbose_name': 'Declaration',
                'verbose_name_plural': 'Declarations',
                'indexes': [models.Index(fields=['is_current'], name='membership__is_curr_cfebd2_idx'), models.Index(fields=['approved_at'], name='membership__approve_8cc1c1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('enrollment',), name='uniq_current_declaration_per_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentPayment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='paid', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('payment_method', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('covers_start', models.DateField(blank=True, null=True)),
                ('covers_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membership.enrollment')),
            ],
            options={
                'verbose_name': 'Enrollment Payment',
                'verbose_name_plural': 'Enrollment Payments',
                'indexes': [models.Index(fields=['status'], name='membership__status_22b7cd_idx'), models.Index(fields=['created_at'], name='membership__created_f7be4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NominatedRep',
            fields=[
                ('nominated_rep_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('position_role', models.TextField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('preferred_contact_method', models.TextField(blank=True, null=True)),
                ('authorisation_confirmation', models.BooleanField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('org_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominated_reps', to='membership.organisation')),
            ],
            options={
                'verbose_name': 'Org - Nominated Rep',
                'verbose_name_plural': 'Org - Nominated Reps',
            },
        ),
        migrations.CreateModel(
            name='AuthorisedSignatory',
            fields=[
                ('authorised_signatory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('digital_signature', models.TextField(blank=True, null=True)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('org_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorised_signatories', to='membership.organisation')),
            ],
            options={
                'verbose_name': 'Org - Authorised Signatory',
                'verbose_name_plural': 'Org - Authorised Signatories',
            },
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('enrollment_code__isnull', False)), fields=('enrollment_code',), name='uniq_enrollment_code'),
        ),
        migrations.AddIndex(
            model_name='nominatedrep',
            index=models.Index(fields=['date_end'], name='membership__date_en_ed10f8_idx'),
        ),
        migrations.AddIndex(
            model_name='authorisedsignatory',
            index=models.Index(fields=['date_end'], name='membership__date_en_5c3c03_idx'),
        ),
    ]
