# Generated by Django 6.0.1 on 2026-02-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationform',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='declarationform',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('declaration_set',), name='uniq_active_declarationform_per_set'),
        ),
    ]
