# Generated by Django 6.0.1 on 2026-02-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_declarationform_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentpayment',
            name='provider',
            field=models.CharField(default='stripe', max_length=32),
        ),
        migrations.AddField(
            model_name='enrollmentpayment',
            name='provider_ref',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('refunded', 'refunded'), ('part_refunded', 'part_refunded')], db_index=True, default='pending', max_length=32),
        ),
    ]
