# Generated by Django 6.0.1 on 2026-02-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_enrollmentpayment_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaration',
            old_name='data_withdrawal_acknowledgement',
            new_name='data_marketing_consent',
        ),
    ]
