# Generated by Django 6.0.1 on 2026-02-24 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_rename_data_withdrawal_acknowledgement_declaration_data_marketing_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='entered_in_register_by_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='entered_in_register_by_name',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
