# Generated by Django 6.0.1 on 2026-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_remove_enrollment_entered_in_register_by_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='date_approved',
        ),
        migrations.AddField(
            model_name='organisation',
            name='people_access_good_food',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organisation',
            name='what_you_do_who_you_support',
            field=models.TextField(blank=True, default=''),
        ),
    ]
