# Generated by Django 6.0.1 on 2026-02-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_remove_enrollment_date_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='alignment_with_fis_mission',
            new_name='food_system_alignment',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='collaboration_interests',
            new_name='org_activity_description',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='collaboration_interests_other',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='healthier_fairer_food_contribution',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='org_activity_beneficiaries_good_food_approach',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='people_access_good_food',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='what_you_do_who_you_support',
        ),
    ]
