# Generated by Django 6.0.1 on 2026-02-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_rename_alignment_with_fis_mission_organisation_food_system_alignment_and_more'),
    ]

    operations = [
    migrations.RenameField(
        model_name="declaration",
        old_name="enrollment",
        new_name="enrolment",
    ),
]
