# Generated by Django 6.0.1 on 2026-02-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_rename_enrollment_id_to_enrolment_id'),
        ('membership', '0012_rename_enrollment_columns_to_enrolment'),
    ]

    operations = [
    ]
