# Generated by Django 6.0.1 on 2026-02-24 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_add_stripe_fields_and_amount_pence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolment',
            options={'verbose_name': 'Enrolment', 'verbose_name_plural': 'Enrolments'},
        ),
        migrations.AlterModelOptions(
            name='enrolmentpayment',
            options={'verbose_name': 'Enrolment Payment', 'verbose_name_plural': 'Enrolment Payments'},
        ),
        migrations.RemoveConstraint(
            model_name='declaration',
            name='uniq_current_declaration_per_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='enrolment',
            name='uniq_enrollment_code',
        ),
        migrations.RenameIndex(
            model_name='enrolmentpayment',
            new_name='membership__status_79e483_idx',
            old_name='membership__status_22b7cd_idx',
        ),
        migrations.RenameIndex(
            model_name='enrolmentpayment',
            new_name='membership__created_d85df7_idx',
            old_name='membership__created_f7be4f_idx',
        ),
        migrations.RemoveField(
            model_name='enrolmentpayment',
            name='amount',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "membership_enrolmentpayment" DROP COLUMN IF EXISTS "enrollment_id";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='enrolmentpayment',
                    name='enrollment',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "membership_enrolmentpayment" '
                        'ADD COLUMN IF NOT EXISTS "amount_pence" integer;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='enrolmentpayment',
                    name='amount_pence',
                    field=models.PositiveIntegerField(default=0),
                    preserve_default=False,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "membership_enrolmentpayment" '
                        'ADD COLUMN IF NOT EXISTS "enrolment_id" bigint;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='enrolmentpayment',
                    name='enrolment',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='payments',
                        to='membership.enrolment',
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "membership_enrolmentpayment" '
                        'ADD COLUMN IF NOT EXISTS "provider_event_id" varchar(255);',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='enrolmentpayment',
                    name='provider_event_id',
                    field=models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "membership_enrolmentpayment" '
                        'ADD COLUMN IF NOT EXISTS "stripe_checkout_session_id" varchar(255);',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='enrolmentpayment',
                    name='stripe_checkout_session_id',
                    field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "membership_enrolmentpayment" '
                        'ADD COLUMN IF NOT EXISTS "stripe_payment_intent_id" varchar(255);',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='enrolmentpayment',
                    name='stripe_payment_intent_id',
                    field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrolments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='membership.party'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='membership.plan'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved_pending_payment', 'Approved - pending payment'), ('active', 'Active'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='enrolmentpayment',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('refunded', 'refunded'), ('part_refunded', 'part_refunded')], db_index=True, default='requested', max_length=40),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='company_charity_number',
            field=models.TextField(blank=True, null=True, verbose_name='Company/Charity Number'),
        ),
        migrations.AddConstraint(
            model_name='declaration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('enrolment',), name='uniq_current_declaration_per_enrolment'),
        ),
    ]
