# Generated by Django 6.0.1 on 2026-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_alter_enrolment_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'DO $$ BEGIN '
                        'IF EXISTS ('
                        "SELECT 1 FROM information_schema.columns "
                        "WHERE table_name='membership_enrolment' AND column_name='enrollment_class'"
                        ') THEN '
                        'ALTER TABLE "membership_enrolment" RENAME COLUMN "enrollment_class" TO "enrolment_class"; '
                        'END IF; '
                        'END $$;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='enrolment',
                    old_name='enrollment_class',
                    new_name='enrolment_class',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'DO $$ BEGIN '
                        'IF EXISTS ('
                        "SELECT 1 FROM information_schema.columns "
                        "WHERE table_name='membership_enrolment' AND column_name='enrollment_code'"
                        ') THEN '
                        'ALTER TABLE "membership_enrolment" RENAME COLUMN "enrollment_code" TO "enrolment_code"; '
                        'END IF; '
                        'END $$;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='enrolment',
                    old_name='enrollment_code',
                    new_name='enrolment_code',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'DO $$ BEGIN '
                        'IF EXISTS ('
                        "SELECT 1 FROM information_schema.columns "
                        "WHERE table_name='membership_enrolment' AND column_name='enrollment_id'"
                        ') THEN '
                        'ALTER TABLE "membership_enrolment" RENAME COLUMN "enrollment_id" TO "enrolment_id"; '
                        'END IF; '
                        'END $$;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='enrolment',
                    old_name='enrollment_id',
                    new_name='enrolment_id',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved_pending_payment', 'Approved - pending payment'), ('active', 'Active'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=40),
        ),
    ]
