# Generated by Django 6.0.1 on 2026-02-24 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_rename_enrollment_class_enrolment_enrolment_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolmentpayment',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrolmentpayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrolmentpayment',
            name='provider_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrolmentpayment',
            name='purpose',
            field=models.CharField(choices=[('membership_fee', 'membership_fee'), ('share_capital', 'share_capital'), ('other', 'other'), ('refund', 'refund')], db_index=True, default='membership_fee', max_length=32),
        ),
        migrations.AddField(
            model_name='enrolmentpayment',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='enrolmentpayment',
            index=models.Index(fields=['enrolment', 'status'], name='membership__enrolme_d48ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolmentpayment',
            index=models.Index(fields=['purpose', 'status'], name='membership__purpose_e51327_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(condition=models.Q(('enrolment_code__isnull', False)), fields=('enrolment_code',), name='uniq_enrolment_code'),
        ),
    ]
