# Generated by Django 6.0.1 on 2026-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_enrolmentpayment_checkout_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='investment_amount_pence',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
