# Generated by Django 6.0.1 on 2026-02-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0019_enrolment_investment_amount_pence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolmentpayment',
            name='checkout_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
