# Generated by Django 6.0.1 on 2026-02-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0020_alter_enrolmentpayment_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_submitted_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='membership_activated_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='payment_requested_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
