# Generated by Django 6.0.1 on 2026-02-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0021_application_application_submitted_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
