# Generated by Django 6.0.1 on 2026-02-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0022_enrolment_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='approved_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrolmentpayment',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
