# Generated by Django 6.0.1 on 2026-02-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0023_enrolment_approved_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolmentpayment',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
