"""
Django settings for fis_membership project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from urllib.parse import urlsplit

APP_VERSION = "staging-2026-02-27"

BASE_DIR = Path(__file__).resolve().parent.parent

# Only load .env for local development.
# On Elastic Beanstalk, environment variables are set in the EB console.
dotenv_path = BASE_DIR / ".env.local"
if dotenv_path.exists():
    load_dotenv(dotenv_path)
    
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    "fis-backend-test-env.eba-phyvw229.eu-west-2.elasticbeanstalk.com",
    ".elasticbeanstalk.com",
    "localhost",
    "127.0.0.1",
    "16.60.141.244",
]
# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'corsheaders',
    "membership.apps.MembershipConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fis_membership.urls'
WSGI_APPLICATION = 'fis_membership.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

sslmode = os.getenv("DB_SSLMODE", "")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": ({"sslmode": sslmode} if sslmode else {}),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000"
    ).split(",")
    if origin.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        ""
    ).split(",")
    if origin.strip()
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

SUBMIT_API_KEY = os.getenv("SUBMIT_API_KEY", "dev-key")

# Turnstile
TURNSTILE_SECRET_KEY = os.getenv("TURNSTILE_SECRET_KEY")
TURNSTILE_SITE_KEY = os.getenv("TURNSTILE_SITE_KEY")
TURNSTILE_VERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify"

# email
SITE_URL = os.getenv("SITE_URL", "http://127.0.0.1:8000")
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_NAME = os.getenv("DEFAULT_FROM_NAME", "The Food Investors Society")
DEFAULT_FROM_ADDRESS = os.getenv("DEFAULT_FROM_ADDRESS") or EMAIL_HOST_USER or "no-reply@localhost"
DEFAULT_FROM_EMAIL = f"{DEFAULT_FROM_NAME} <{DEFAULT_FROM_ADDRESS}>"
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))

# --- Brevo transactional email -------------------------------------------------
# Used for receipts/notifications so they send from an authenticated sender
# (fixes the Gmail-SMTP spam placement). If BREVO_API_KEY is unset, the email
# helpers transparently fall back to Django's send_mail (EMAIL_BACKEND above),
# so nothing breaks before Brevo is wired up on the environment.
BREVO_API_KEY = os.getenv("BREVO_API_KEY", "")
BREVO_API_URL = os.getenv("BREVO_API_URL", "https://api.brevo.com/v3/smtp/email")
# Sender must be a verified sender/domain in Brevo (Senders & IPs).
BREVO_SENDER_EMAIL = os.getenv("BREVO_SENDER_EMAIL", "thefoodinvestorssociety@gmail.com")
BREVO_SENDER_NAME = os.getenv("BREVO_SENDER_NAME", "The Food Investors Society")
# Integer template IDs from Brevo > Transactional > Templates. 0 => not set.
BREVO_DONATION_RECEIPT_TEMPLATE_ID = int(os.getenv("BREVO_DONATION_RECEIPT_TEMPLATE_ID", "0")) or None
BREVO_APPLICATION_SUBMITTED_TEMPLATE_ID = int(os.getenv("BREVO_APPLICATION_SUBMITTED_TEMPLATE_ID", "0")) or None
BREVO_PAYMENT_REQUESTED_TEMPLATE_ID = int(os.getenv("BREVO_PAYMENT_REQUESTED_TEMPLATE_ID", "0")) or None
BREVO_MEMBERSHIP_PAYMENT_RECEIVED_TEMPLATE_ID = int(os.getenv("BREVO_MEMBERSHIP_PAYMENT_RECEIVED_TEMPLATE_ID", "0")) or None
BREVO_MEMBERSHIP_ACTIVATED_TEMPLATE_ID = int(os.getenv("BREVO_MEMBERSHIP_ACTIVATED_TEMPLATE_ID", "0")) or None
BREVO_NEWSLETTER_LIST_ID = int(os.getenv("BREVO_NEWSLETTER_LIST_ID", "2"))

FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "https://fis-website-f3k.pages.dev")
BACKEND_BASE_URL = os.getenv("BACKEND_BASE_URL", SITE_URL)

frontend_origin = urlsplit(FRONTEND_BASE_URL)

if frontend_origin.scheme and frontend_origin.netloc:
    frontend_origin_value = (
        f"{frontend_origin.scheme}://{frontend_origin.netloc}"
    )

    if frontend_origin_value not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(frontend_origin_value)

    if frontend_origin_value not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(frontend_origin_value)

# Stripe
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

# where Stripe sends people after paying / cancelling --> NEEDS UPDATING ONCE HOSTED ON AWS 
STRIPE_SUCCESS_URL = os.getenv("STRIPE_SUCCESS_URL", f"{FRONTEND_BASE_URL}/payment-success.html?payment_id={{payment_id}}")
STRIPE_CANCEL_URL = os.getenv("STRIPE_CANCEL_URL", f"{FRONTEND_BASE_URL}/payment-cancelled.html?payment_id={{payment_id}}")
STRIPE_CURRENCY = "gbp"

THANKS_BASE = os.getenv("THANKS_BASE", f"{FRONTEND_BASE_URL}/thank-you.html")
